swagger: '2.0'
info:
  title: 'Update Electro Scooter'
  description: 'Updates an existing Electro Scooter.'
  version: '1.0'
consumes:
  - 'application/json'
produces:
  - 'application/json'
parameters:
  - in: 'path'
    name: 'scooter_id'
    required: true
    type: 'integer'
    description: 'ID of the Electro Scooter.'
  - in: 'body'
    name: 'body'
    required: true
    schema:
      id: ElectroScooter
      properties:
        name:
          type: 'string'
          description: 'Name of the Electro Scooter.'
        battery_level:
          type: 'number'
          format: 'float'
          description: 'Battery level of the Electro Scooter.'
responses:
  '200':
    description: 'Electro Scooter updated successfully.'
  '404':
    description: 'Electro Scooter not found.'
  '500':
    description: 'Internal Server Error.'
